export const MARKET_CALENDAR = [
  {
    bass_dt: new Date("2024-10-04"),
    wday_dvsn_cd: "06",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-05"),
    wday_dvsn_cd: "07",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-06"),
    wday_dvsn_cd: "01",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-07"),
    wday_dvsn_cd: "02",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-08"),
    wday_dvsn_cd: "03",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-09"),
    wday_dvsn_cd: "04",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-10"),
    wday_dvsn_cd: "05",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-11"),
    wday_dvsn_cd: "06",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-12"),
    wday_dvsn_cd: "07",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-13"),
    wday_dvsn_cd: "01",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-14"),
    wday_dvsn_cd: "02",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-15"),
    wday_dvsn_cd: "03",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-16"),
    wday_dvsn_cd: "04",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-17"),
    wday_dvsn_cd: "05",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-18"),
    wday_dvsn_cd: "06",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-19"),
    wday_dvsn_cd: "07",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-20"),
    wday_dvsn_cd: "01",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-21"),
    wday_dvsn_cd: "02",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-22"),
    wday_dvsn_cd: "03",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-23"),
    wday_dvsn_cd: "04",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-24"),
    wday_dvsn_cd: "05",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-25"),
    wday_dvsn_cd: "06",
    bzdy_yn: true,
    tr_day_yn: true,
    opnd_yn: true,
    sttl_day_yn: true,
  },
  {
    bass_dt: new Date("2024-10-26"),
    wday_dvsn_cd: "07",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
  {
    bass_dt: new Date("2024-10-27"),
    wday_dvsn_cd: "01",
    bzdy_yn: false,
    tr_day_yn: true,
    opnd_yn: false,
    sttl_day_yn: false,
  },
];
